-- Creamos la base de datos
DROP DATABASE IF EXISTS blog;
CREATE DATABASE blog DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;
CREATE USER IF NOT EXISTS blog@localhost IDENTIFIED BY 'blog2021';
GRANT ALL ON blog.* TO 'blog'@'localhost';

use blog;
-- Creamos las tablas
CREATE TABLE articulos (
	id INT NOT NULL AUTO_INCREMENT,
	titulo VARCHAR(120) NOT NULL,
	fecha DATETIME NOT NULL,
	contenido VARCHAR(1024) NOT NULL,
	PRIMARY KEY(id)
) ENGINE = INNODB;

INSERT INTO articulos VALUES
(NULL,'Sanidad recomienda no celebrar las manifestaciones del 8 de marzo: “No ha lugar”','2021-02-24 21:29:59','El Ministerio de Sanidad ha recomendado este miércoles que no se celebren las manifestaciones del 8-M ante la situación epidemiológica, pese a que España ha salido de la situación de riesgo extremo. La ministra Carolina Darias ha asegurado, tras el Consejo Interterritorial de Salud, que “no ha lugar” a celebrar las marchas por el Día Internacional de la Mujer. Darias ha hecho estas declaraciones horas después de que el delegado del Gobierno en Madrid, José Manuel Franco, anunciara que prohibirá todas las convocatorias para esa fecha en la capital (que sigue en riesgo extremo junto con el País Vasco) que tengan una previsión superior a 500 asistentes, cumpliendo el criterio de la Consejería de Sanidad, por lo que “rotundamente no habrá” una gran protesta feminista en la capital, como la del año pasado o años precedentes'),
(NULL,'La lentitud en las campañas de vacunación obliga a Europa a mantener las restricciones en los viajes','2021-02-24 19:00:54','La segunda cumbre de la Unión Europea sobre la pandemia de covid-19 desde comienzos de año se saldará este jueves con una prolongación de las restricciones a todos los viajes considerados no esenciales, tanto desde un país comunitario a otro como los procedentes de un país tercero. El lento ritmo de vacunación y el temor a las nuevas variantes del virus obliga a los 27 socios de la Unión a restringir los viajes trasnfronterizos, y está multiplicando los roces por la desconfianza entre unos y otros.'),
(NULL,'Atalanta - Real Madrid en directo, la Champions League en vivo','2021-02-24 20:25:02','Los octavos de final de la Champions no han empezado nada bien para los equipos españoles. Tanto el Barcelona como el Sevilla y el Atlético perdieron en sus duelos de ida en su casa, complicándose el pase a la siguiente ronda.'),
(NULL,'Sánchez anuncia 11.000 millones para hostelería y turismo sin detallar ni el calendario ni el formato de las ayudas','2021-02-24 20:17:43','El presidente del Gobierno, Pedro Sánchez, ha anunciado este miércoles en el Congreso un paquete de 11.000 millones de euros para “empresas, pymes y trabajadores autónomos” centradas en los sectores del “turismo, la hostelería y la restauración”. “No queremos solamente salvar empresas, sino reforzarlas”, ha dicho Sánchez. El anuncio se produce en pleno debate sobre la necesidad de que el Estado destine ayudas directas a salvar empresas, sobre todo pequeños negocios, asfixiados por las restricciones impuestas por la pandemia.'),
(NULL,'Un año fumigando contra el coronavirus y otros casos de “teatro pandémico”','2021-02-24 09:43:53','La Administración estadounidense decidió fumigar las instalaciones de la Casa Blanca tras la marcha de Donald Trump. Así, horas antes de que Joe Biden ocupara la residencia presidencial, un equipo de operarios se dedicó a nebulizar desinfectante por las estancias. La semana pasada, los británicos veían cómo su primer ministro, Boris Johnson, se esmeraba con afán en la limpieza del asiento de una silla. Un año después de que un nuevo coronavirus sometiera al mundo, se toman demasiadas medidas de cara a la galería.'),
(NULL,'Maduro ordena la expulsión de la embajadora de la Unión Europea en Venezuela ','2021-02-24 20:23:20','El chavismo elevó este miércoles la tensión con Bruselas con un gesto que pretende demostrar el rechazo del Gobierno de Nicolás Maduro a toda acción internacional contra el régimen. Venezuela ordenó formalmente la expulsión de la embajadora de la Unión Europea, Isabel Brilhante, y le dio un plazo de 72 horas para abandonar su territorio.'),
(NULL,'24.000 profesores técnicos de FP subirán de categoría al integrarse en el cuerpo de docentes de secundaria','2021-02-24 21:11:17','Unos 24.100 miembros del cuerpo de profesores técnicos de Formación Profesional se integrarán en el cuerpo de profesores de secundaria. El cambio, previsto en la nueva ley educativa, la Lomloe, supone un ascenso de categoría dentro del escalafón de los empleados públicos y, con ello, un aumento salarial. La integración es una reivindicación histórica de este colectivo docente. El principal requisito es tener un título universitario, con el que cuentan cerca del 85% de estos profesores. Los que no lo tienen, unos 4.250, continuarán con sus condiciones actuales hasta que se jubilen.'),
(NULL,'Primera señal de una estrella invisible que puede explicar el enigma de la materia oscura ','2021-02-24 19:25:36','Una señal de ondas gravitacionales generada hace más de 7.000 millones de años —la mayor que se ha captado hasta la fecha— se ha convertido en uno de los fenómenos más controvertidos y apasionantes de la física actual, pues con las leyes del universo en la mano no debería existir.'),
(NULL,'El fútbol español se prepara para dar la vuelta al mundo','2021-02-24 09:05:45','El primer recuerdo del fútbol español en América no es el más grato. 19 jugadores vascos, un entrenador británico –el famoso ‘Míster’ Harris– y un periodista zarparon el 27 de junio de 1922 desde Lisboa y cruzaron el Atlántico a bordo del Cap Polonio para arribar a Buenos Aires (Argentina) dos semanas más tarde, el 13 de julio. Fueron recibidos por gran parte de la sociedad vasca que había emigrado al Río de la Plata, y casi sin descansar, se midieron con una selección porteña.'),
(NULL,'Miley Cyrus, la nueva diva de los viejos rockeros','2021-02-24 16:33:27','La cantante culmina su transformación de edulcorado ídolo juvenil de Hannah Montana a celebrada rockera. Tras su éxito en el concierto previo a la Super Bowl, prepara un disco de versiones de Metallica.');